EnableMana: true
  # Mana functions as ammunition for each weapon. If set to false, Mana will be ignored.
  # Mana recipe layout representing crafting grid positions:
  # 1 2 3
  # 4 5 6
  # 7 8 9
  # If no item is specified for a certain position, that slot will be empty in the crafting grid.
Manarecipe:
  1: "GOLD_INGOT"
  2: "CRYING_OBSIDIAN"
  3: "GOLD_INGOT"
  4: "DIAMOND"
  5: "IRON_INGOT"
  6: "DIAMOND"
  7: "GOLD_INGOT"
  8: "CRYING_OBSIDIAN"
  9: "GOLD_INGOT"

# Enables or disables weapons in specific worlds.
EnableWeaponsInEnd: false
EnableWeaponsInOverworld: true
EnableWeaponsInNether: false

# Safe zone is a region where weapons have no effect; you can set up one safe zone per world.
# loc1 and loc2 define two opposite corners of the safe zone with x, y, z coordinates.
# If the world has a different name, specify it with `world` for both loc1 and loc2.
Safezone:
  # Two corners in the overworld
  Overworld:
    loc1:
      ==: org.bukkit.Location
      world: world
      x: -304
      y: 125
      z: -733
    loc2:
      ==: org.bukkit.Location
      world: world
      x: -234
      y: 75
      z: -803
  # Two corners in the nether
  Nether:
    loc1:
      ==: org.bukkit.Location
      world: world_nether
      x: 0
      y: 0
      z: 0
    loc2:
      ==: org.bukkit.Location
      world: world_nether
      x: 0
      y: 0
      z: 0
  # Two corners in the end
  End:
    loc1:
      ==: org.bukkit.Location
      world: world_the_end
      x: 0
      y: 0
      z: 0
    loc2:
      ==: org.bukkit.Location
      world: world_the_end
      x: 0
      y: 0
      z: 0

# Settings for enabling weapons in controlled PvP zones (CPvP).
EnableWeaponsInCPVP: true
# Two corners in the overworld for normal PvP; used only if EnableWeaponsInCPVP is set to false.
# Follows the same rules as the safe zone. Safe zones can exist inside normal PvP areas and will still function.
Normalpvp:
  loc1:
    ==: org.bukkit.Location
    world: world
    x: -304
    y: 125
    z: -733
  loc2:
    ==: org.bukkit.Location
    world: world
    x: -234
    y: 75
    z: -803

# Configuration settings for each weapon.
# Most numbers specified here are defaults that will be used if no values are entered.
# Cooldown and Duration are measured in seconds.
# Radius values are measured in blocks.
# Damage and Heal are in hit points.

Shadowdagger:
  Cooldown: 60
  # Maxdistance defines how far the player can teleport. If Maxdistance is 60, the player can teleport
  # multiple times until the total distance teleported reaches 60 blocks or the cooldown ends.
  Maxdistance: 60
  # Enable determines whether the weapon is enabled. If it’s too overpowered, it can be easily disabled.
  Enable: true

Vampireblade:
  Cooldown: 60
  # Radius defines the area around the player where the ability is active.
  Radius: 7
  # Duration specifies how long the ability lasts.
  Duration: 10
  # Damageandheal is the damage dealt every second to players within the radius,
  # and the health restored to the user for each affected player.
  Damageandheal: 2
  Enable: true

Flamingaxe:
  Cooldown: 60
  # Smallerradius is a smaller radius around the player where greater damage and knockback are dealt.
  # This smaller radius does not extend beyond the general Radius.
  Smallerradius: 6
  # Smallerradiusdamage specifies the damage dealt within the smaller radius.
  Smallerradiusdamage: 15
  # Radius is the general radius within which players are affected.
  Radius: 9
  # Damage is the damage dealt to players within the radius, but outside of the smaller radius.
  Damage: 10
  Enable: true

Coldstaff:
  Cooldown: 60
  Radius: 9
  Duration: 5
  Enable: true

Staffofhealing:
  Cooldown: 60
  # Heal is the amount of health points restored when the ability is used.
  Heal: 20
  Enable: true

Shieldofeternity:
  Cooldown: 60
  Radius: 6
  Duration: 10
  Enable: true
















































