name: CustomWeapons
version: '${project.version}'
main: com.lupino.customweapons.CustomWeapons
api-version: '1.20'
commands:
  giveweapons:
    description: gives player with op all custom weapons
    permission: op
